### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by BenRacicot** [bchynds/LiDAR-Importer#2]
Hello, I just wanted to see what the status of this project is? I saw a thread where the author mentioned that it was being discontinued but a newer version for point files was being built by students in 2015. I think this project is hugely needed in the Blender community. 

I've got the addon loading but when activated I get:
![screen shot 2016-03-24 at 11 36 49 am](https://cloud.githubusercontent.com/assets/1815385/14022108/be06a74c-f1b4-11e5-8cb4-143166693f76.png)

**Comment by bchynds** [comment]
Hi Ben.  I haven't gotten around to fixing the add-on yet, but if you have any experience with python it's essentially just a matter of using the python modules for liblas (https://github.com/libLAS/libLAS/tree/master/python/liblas) to iterate through the point cloud data and constructing the blender scene from it.  I'm not very skilled with python and what I built was about a few weeks worth of learning everything from scratch.  I do plan to revisit this code again, but unfortunately I've been wrapped up with work lately.

**Comment by bchynds** [comment]
Just want to post a followup to this issue.  There is now complete build and install instructions in the Readme that should resolve anyone encountering this issue.  Thanks for your patience!
